# Generated by Django 4.2.5 on 2023-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0006_post_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tag_set",
            field=models.ManyToManyField(blank=True, to="instagram.tag"),
        ),
    ]
